;;; debugger.el --- All necessary tools for debugging -*- lexical-binding: t; -*-

;;; Commentary:
;;
;; This file configures `dape` (Debug Adapter Protocol for Emacs).
;; It replaces `dap-mode` with a native, lightweight, and strictly declarative
;; configuration architecture based on Emacs 29+ JSON-RPC.
;;
;; Key frameworks supported:
;; 1. PHP: Symfony (Docker Skeleton), Laravel (Sail), Laminas (Local).
;; 2. Go: Delve (dlv).
;; 3. Python: debugpy (Flask, Django).
;; 4. JS/TS: Node.js, NPM Scripts, Chrome Frontend.
;; 5. Rust/C++: LLDB.
;;
;;; Code:

(defvar jmc-dap-prefix-map)
(defvar dape-buffer-window-arrangement)
(defvar dape-inlay-hints)
(defvar dape-configs)

(declare-function projectile-project-root "projectile")
;; Generated by `defhydra' in the dape `:config' block below.
(declare-function jmc-dape-hydra/body "debugger")

;; =============================================================================
;; UTILITY FUNCTIONS
;; =============================================================================

(defun jmc-get-workspace-root ()
  "Grab the project root via Projectile, falling back to the current directory.
Projectile is this config's single source of truth for project
boundaries (extra root markers like `.envrc'/`go.mod' are registered
with it in projects.el). The old project.el-based version could resolve
a different root than the `s-p' commands for the same buffer."
  (if-let* ((root (and (fboundp 'projectile-project-root)
                       (projectile-project-root))))
      (expand-file-name root)
    (expand-file-name default-directory)))

(defun jmc-python-venv-bin ()
  "Helper to find the local .venv python binary for Dape."
  (let ((venv (locate-dominating-file default-directory ".venv")))
    (if venv (expand-file-name ".venv/bin/python" venv) "python3")))

;; =============================================================================
;; DAPE CORE & KEYBINDINGS
;; =============================================================================

(use-package dape
  ;; Defer loading until a debug command is actually invoked.
  ;; -> Without this, dape (and its jsonrpc machinery) loaded EAGERLY at
  ;;    startup; the `:commands` list creates autoloads for every key in the
  ;;    prefix map below, so the keys work while startup stays fast.
  :defer t
  :commands (dape dape-quit dape-breakpoint-toggle dape-breakpoint-remove-all
		  dape-continue dape-next dape-step-in dape-step-out
		  dape-info dape-restart)
  :preface
  (defun jmc-dape-hydra-open ()
    "Load dape (defining its hydra) and open the debug hydra."
    (interactive)
    (require 'dape)
    (jmc-dape-hydra/body))
  :init
  ;; --- Keybinding Setup ---
  ;; We keep your exact C-c d prefix, mapped to dape's native functions.
  ;; (docker moved to `C-c D` in languages.el, so this prefix is now
  ;;  unambiguously ours.)
  (define-prefix-command 'jmc-dap-prefix-map)
  (global-set-key (kbd "C-c d") 'jmc-dap-prefix-map)

  (define-key jmc-dap-prefix-map (kbd "d") #'dape)
  (define-key jmc-dap-prefix-map (kbd "r") #'dape-quit)
  (define-key jmc-dap-prefix-map (kbd "b") #'dape-breakpoint-toggle)
  (define-key jmc-dap-prefix-map (kbd "B") #'dape-breakpoint-remove-all)
  (define-key jmc-dap-prefix-map (kbd "c") #'dape-continue)
  (define-key jmc-dap-prefix-map (kbd "n") #'dape-next)
  (define-key jmc-dap-prefix-map (kbd "i") #'dape-step-in)
  (define-key jmc-dap-prefix-map (kbd "o") #'dape-step-out)
  (define-key jmc-dap-prefix-map (kbd "w") #'dape-info)
  (define-key jmc-dap-prefix-map (kbd "R") #'dape-restart)
  ;; The hydra: every action above as a SINGLE key while it's open.
  (define-key jmc-dap-prefix-map (kbd "h") #'jmc-dape-hydra-open)

  :custom
  ;; --- UI Config ---
  ;; Show the REPL and info buffers (locals, breakpoints, stack) on the RIGHT.
  ;;
  ;; FIXED: the old config tried to do this with a `display-buffer-alist`
  ;; rule matching the buffer name "*dape-info*" — but dape's info buffers
  ;; are actually named "*dape-info Stack*", "*dape-info Breakpoints*", etc.
  ;; (verified upstream), so the rule NEVER matched and we were silently on
  ;; dape's default 'left layout. `dape-buffer-window-arrangement` is the
  ;; supported knob. For finer per-buffer control, dape tags each info
  ;; buffer with a display-buffer `category` (dape-info-0, dape-info-1, ...)
  ;; usable from `display-buffer-alist`.
  (dape-buffer-window-arrangement 'right)

  ;; Enable inline variable values in your code while debugging.
  (dape-inlay-hints t)

  ;; Make PROJECTILE the root authority for dape too. The stock configs we
  ;; splice below resolve their `:cwd'/`command-cwd' through dape's
  ;; `dape-cwd'/`dape-command-cwd', which call this function — by default
  ;; it guesses via project.el, which can disagree with projectile's root
  ;; (projectile knows `.envrc'/`go.mod' markers). Pointing it at our
  ;; helper gives every debug session the same root as the `s-p' commands.
  (dape-cwd-function #'jmc-get-workspace-root)

  :config
  ;; NOTE: no hook is needed to open the info windows — `dape-start-hook`
  ;; DEFAULTS to '(dape-repl dape-info), so both open automatically when a
  ;; session starts. (The old extra add-hook was redundant. If you'd rather
  ;; not have the REPL pop up, set: (setq dape-start-hook '(dape-info)).)

  ;; --- Cleanup on quit ---
  ;; FIXED: the old cleanup used `dape-kill-hook`, which DOES NOT EXIST in
  ;; dape (its hooks are dape-start-hook, dape-stopped-hook,
  ;; dape-update-ui-hook, dape-display-source-hook, dape-compile-hook), and
  ;; it looked for a buffer literally named "*dape-info*", which also never
  ;; exists — so it was doubly dead. We advise `dape-quit` instead and match
  ;; the real buffer-name prefix.
  (defun jmc-dape-cleanup-windows-a (&rest _)
    "Close all dape info/REPL windows and buffers after quitting."
    (dolist (buf (buffer-list))
      (when (string-match-p "\\`\\*dape-\\(info\\|repl\\)" (buffer-name buf))
	(dolist (win (get-buffer-window-list buf nil t))
	  (when (window-live-p win)
	    (ignore-errors (delete-window win))))
	(kill-buffer buf))))

  (advice-add 'dape-quit :after #'jmc-dape-cleanup-windows-a)

  ;; --- Debug hydra -----------------------------------------------------
  ;; One-key stepping: `C-c d h' opens it, then n/i/o/c drive the session
  ;; without re-typing the prefix — the replacement for the `dap-hydra'
  ;; lost in the dap-mode -> dape migration. RED hydra: any non-hydra key
  ;; (e.g. jumping to another window, editing) exits the menu and does its
  ;; normal thing; `C-c d h' brings it right back.
  ;; -> Defined in `:config' (not top level): modules load before Elpaca
  ;;    installs packages, so `defhydra' only exists at runtime.
  (defhydra jmc-dape-hydra (:color red :hint nil)
    "
 ^Stepping^         ^Breakpoints^      ^Session^
 _n_: next          _b_: toggle        _d_: start / select config
 _i_: step in       _B_: remove all    _R_: restart
 _o_: step out      ^ ^                _w_: info windows
 _c_: continue      ^ ^                _r_: quit session
"
    ("n" dape-next)
    ("i" dape-step-in)
    ("o" dape-step-out)
    ("c" dape-continue)
    ("b" dape-breakpoint-toggle)
    ("B" dape-breakpoint-remove-all)
    ("d" dape)
    ("R" dape-restart)
    ("w" dape-info)
    ("r" dape-quit :color blue)
    ("q" nil))

  ;; =============================================================================
  ;; LANGUAGE ADAPTER CONFIGURATIONS
  ;; =============================================================================

  ;; --------------------------------------------------------------
  ;; PHP (Symfony, Laravel)
  ;; --------------------------------------------------------------
  (add-to-list 'dape-configs
	       `(php-local
		 modes (php-mode php-ts-mode)
		 port 9003
		 :type "php"
		 :request "launch"
		 :name "PHP :: Listen for XDebug (Local)"
		 :sourceMaps t))

  (add-to-list 'dape-configs
	       `(php-symfony-docker
		 modes (php-mode php-ts-mode)
		 port 9003
		 :type "php"
		 :request "launch"
		 :name "PHP :: Symfony Docker (Skeleton)"
		 :hostname "0.0.0.0"
		 :pathMappings ,(lambda () `(:/app ,(jmc-get-workspace-root)))
		 :sourceMaps t))

  (add-to-list 'dape-configs
	       `(php-laravel-sail
		 modes (php-mode php-ts-mode)
		 port 9003
		 :type "php"
		 :request "launch"
		 :name "PHP :: Laravel Sail"
		 :pathMappings ,(lambda () `(:/var/www/html ,(jmc-get-workspace-root)))
		 :sourceMaps t))

  ;; --------------------------------------------------------------
  ;; PYTHON (Flask, Django)
  ;; --------------------------------------------------------------
  (add-to-list 'dape-configs
	       `(python-flask
		 modes (python-mode python-ts-mode)
		 command jmc-python-venv-bin
		 command-args ("-m" "debugpy.adapter")
		 :type "python"
		 :request "launch"
		 :module "flask"
		 :args ["run" "--no-debugger" "--no-reload"]
		 :cwd jmc-get-workspace-root
		 :env (:FLASK_APP "app.py" :FLASK_DEBUG "1" :PYTHONPATH ".")))

  (add-to-list 'dape-configs
	       `(python-django
		 modes (python-mode python-ts-mode)
		 command jmc-python-venv-bin
		 command-args ("-m" "debugpy.adapter")
		 :type "python"
		 :request "launch"
		 :program "manage.py"
		 :args ["runserver" "--noreload"]
		 :cwd jmc-get-workspace-root
		 :django t))

  ;; --------------------------------------------------------------
  ;; JAVASCRIPT & TYPESCRIPT (Node.js & Chrome)
  ;; --------------------------------------------------------------
  ;;
  ;; IMPORTANT: our overrides must come BEFORE the `,@(alist-get ...)`
  ;; splice of the stock config. dape reads these plists with `plist-get',
  ;; which returns the FIRST occurrence of a key — any key listed after the
  ;; splice that the base config also defines is silently ignored. That bug
  ;; previously pinned `modes' to the base's (js-mode js-ts-mode), hiding
  ;; these configs from typescript/tsx buffers, and kept js-npm-script on
  ;; the base's :console "internalConsole".
  (add-to-list 'dape-configs
	       `(js-node-file
		 modes (js-ts-mode typescript-ts-mode tsx-ts-mode)
		 :name "JS/TS :: Run Current File"
		 :sourceMaps t
		 ,@(alist-get 'js-debug-node dape-configs)))

  (add-to-list 'dape-configs
	       `(js-tsx-file
		 modes (typescript-ts-mode tsx-ts-mode)
		 :name "JS/TS :: Run Raw TypeScript (tsx)"
		 :type "pwa-node"
		 :request "launch"
		 :cwd jmc-get-workspace-root
		 ;; Inject the tsx loader into the native Node process
		 :runtimeExecutable "node"
		 :runtimeArgs ["--import" "tsx"]
		 :program ,(lambda () (buffer-file-name))
		 :sourceMaps t
		 :resolveSourceMapLocations ["${workspaceFolder}/**" "!**/node_modules/**"]
		 ,@(alist-get 'js-debug-node dape-configs)))

  (add-to-list 'dape-configs
	       `(js-npm-script
		 modes (js-ts-mode typescript-ts-mode tsx-ts-mode)
		 :name "JS/TS :: NPM Run Script"
		 :runtimeExecutable "npm"
		 :runtimeArgs ["run" "dev"]
		 :console "integratedTerminal"
		 ,@(alist-get 'js-debug-node dape-configs)))

  (add-to-list 'dape-configs
	       `(js-chrome-frontend
		 modes (js-ts-mode typescript-ts-mode tsx-ts-mode)
		 :name "JS/TS :: Chrome Debugger"
		 :url "http://localhost:3000"
		 ,@(alist-get 'js-debug-chrome dape-configs)))

  ;; --------------------------------------------------------------
  ;; GO (Delve)
  ;; --------------------------------------------------------------
  ;; Same first-key-wins rule as the JS configs above: overrides BEFORE the
  ;; splice. Previously the base dlv config's `:program "."' shadowed the
  ;; lambdas below, so all three variants debugged the project root — the
  ;; "current file"/"current package"/"tests" distinction never applied.
  (add-to-list 'dape-configs
	       `(go-current-file
		 modes (go-mode go-ts-mode)
		 :name "Go :: Debug (Current File)"
		 :request "launch"
		 :mode "debug"
		 :program ,(lambda () (buffer-file-name))
		 :cwd jmc-get-workspace-root
		 ,@(alist-get 'dlv dape-configs)))

  (add-to-list 'dape-configs
	       `(go-package
		 modes (go-mode go-ts-mode)
		 :name "Go :: Debug (Current Package)"
		 :request "launch"
		 :mode "debug"
		 :program ,(lambda () (file-name-directory (buffer-file-name)))
		 :cwd jmc-get-workspace-root
		 ,@(alist-get 'dlv dape-configs)))

  (add-to-list 'dape-configs
	       `(go-test
		 modes (go-mode go-ts-mode)
		 :name "Go :: Debug (Tests)"
		 :request "launch"
		 :mode "test"
		 :program ,(lambda () (file-name-directory (buffer-file-name)))
		 :cwd jmc-get-workspace-root
		 ,@(alist-get 'dlv dape-configs)))

  ;; --------------------------------------------------------------
  ;; RUST (CodeLLDB)
  ;; --------------------------------------------------------------
  (add-to-list 'dape-configs
	       `(rust-codelldb
		 modes (rustic-mode rust-ts-mode)
		 ensure dape-ensure-command
		 command "codelldb"
		 command-args ("--port" :autoport)
		 port :autoport
		 :type "lldb"
		 :request "launch"
		 :cwd jmc-get-workspace-root
		 compile "cargo build"
		 ;; Dynamically build the path to the compiled binary based on the folder name
		 :program ,(lambda ()
			     (let ((root (jmc-get-workspace-root)))
			       (concat root "target/debug/"
				       (file-name-nondirectory
					(directory-file-name root))))))))

;; =============================================================================
;; FINALIZE
;; =============================================================================

(provide 'debugger)
;;; debugger.el ends here
