;;; editor.el --- General editor settings and behaviors -*- lexical-binding: t; -*-

;;; Commentary:
;;
;; This file configures the core text editing experience in Emacs.
;;
;; It focuses on the *act* of editing text itself, independent of any specific
;; programming language. This includes:
;;
;; 1. Core Behaviors: File handling, auto-reloading, UTF-8, and backups.
;; 2. Session & History: Remembering command history and cursor positions.
;; 3. Visual Aids: Line numbers, word wrap, indent guides, and bracket pairing.
;; 4. Editing Enhancements: Multiple cursors, semantic expansion, rapid jumping
;;    (`avy`), easy commenting, and an advanced undo tree (`vundo`).
;;
;;; Code:

;; =============================================================================
;; COMPILER DECLARATIONS (SILENCE WARNINGS)
;; =============================================================================

(defvar wgrep-auto-save-buffer)
(defvar vundo-glyph-alist)
(defvar vundo-unicode-symbols)
(defvar electric-pair-pairs)
(defvar no-littering-var-directory)
(defvar no-littering-etc-directory)

(declare-function electric-pair-conservative-inhibit "elec-pair")
(declare-function global-hl-todo-mode "hl-todo")
(declare-function whole-line-or-region-global-mode "whole-line-or-region")
(declare-function drag-stuff-global-mode "drag-stuff")
(declare-function drag-stuff-define-keys "drag-stuff")
(declare-function evilnc-default-hotkeys "evil-nerd-commenter")
;; Generated by `defhydra' in the multiple-cursors `:config' block below.
(declare-function jmc-mc-hydra/body "editor")
(declare-function mc/num-cursors "multiple-cursors-core")

;; =============================================================================
;; CORE EDITOR BEHAVIOR
;; =============================================================================

;; Ensure all text files end with a single empty newline (POSIX standard).
(setq require-final-newline t)

;; Quit Emacs silently, even if sub-processes (like LSP or terminals) are running.
(setq confirm-kill-processes nil)

;; Enable CUA (Common User Access) mode.
;; -> Makes Emacs respect standard OS shortcuts: `C-x` (cut), `C-c` (copy), `C-v` (paste).
(cua-mode 1)

;; --- Auto-revert Mode ---
;; Automatically reload files if they are modified by an external program (e.g., `git checkout`).
(setq-default auto-revert-avoid-polling t)
(setq auto-revert-interval 5)
;; NOTE: `auto-revert-check-vc-info' is deliberately OFF (default). Turning
;; it on made every 5-second auto-revert poll ALSO refresh git state for
;; every buffer — a steady background git tax in large repos — just to keep
;; the mode-line branch name current in real time. The branch display still
;; updates on save, revert, and every magit operation (diff-hl refreshes on
;; magit hooks too).
(global-auto-revert-mode 1)

;; Disable the archaic convention of requiring two spaces after a period.
(setq-default sentence-end-double-space nil)

;; Disable automatic backup files (e.g., `file.txt~`).
;; -> We rely on Git for version control; these files just create clutter.
(setq make-backup-files nil)

;; NOTE: no `delete-selection-mode` here — CUA mode (above) already makes
;; typing replace the active region (`cua-delete-selection', on by
;; default), so enabling both was redundant.

;; --- Encoding ---
;; Force UTF-8 encoding everywhere to ensure special characters always render correctly.
(prefer-coding-system 'utf-8)
(set-default-coding-systems 'utf-8)

;; =============================================================================
;; HISTORY & SESSION PERSISTENCE
;; =============================================================================

;; Save Minibuffer History.
;; -> Remembers your previous `M-x` commands and search queries across Emacs restarts.
(use-package savehist
  :ensure nil ; Built-in
  :init (savehist-mode 1)
  :config (setq history-length 1000)) ; Retain the last 1000 history items.

;; Save Cursor Position.
;; -> When you reopen a file, your cursor will be exactly where you left it.
(use-package saveplace
  :ensure nil ; Built-in
  :init (save-place-mode 1))

;; Track recently opened files (supercharges consult-buffer, and feeds the
;; welcome screen's "Recent Files" section).

(defun jmc-recentf-exclude-dir (dir)
  "Return a regexp excluding DIR from recentf under ALL its spellings.
recentf stores entries ABBREVIATED — `recentf-filename-handlers'
defaults to `abbreviate-file-name' since Emacs 28 — so a regexp built
from `expand-file-name' alone silently fails to match the \"~/...\"
form the list actually contains. On top of that, `user-emacs-directory'
is reached through a stow symlink, so the same file can be recorded
under the resolved dotfiles path too. Cover the expanded, abbreviated,
and truename spellings in one anchored alternation."
  (let* ((expanded (expand-file-name dir))
         (resolved (file-truename expanded)))
    (concat "\\`"
            (regexp-opt (delete-dups
                         (list expanded
                               (abbreviate-file-name expanded)
                               resolved
                               (abbreviate-file-name resolved)))))))

(use-package recentf
  :ensure nil ; Built-in
  :init
  ;; Settings must be in place BEFORE the mode starts: enabling
  ;; `recentf-mode' loads the saved list and runs its cleanup pass right
  ;; there (`recentf-auto-cleanup' defaults to 'mode) — with the old
  ;; :config ordering these were applied AFTER that, so exclusions would
  ;; never have pruned the saved list. Which is also why there were no
  ;; exclusions: internal machinery (treemacs-persist, package sources)
  ;; kept surfacing as "recent files" on the startup screen.
  (setq recentf-max-menu-items 100
        recentf-max-saved-items 1000
        recentf-exclude
        (list
         ;; Emacs-internal state. no-littering routes save-files into
         ;; var/ and config-files into etc/; .cache/ holds what ignores
         ;; that convention (treemacs-persist); elpaca/ and elpa/ are
         ;; package SOURCES, visited when debugging into a library —
         ;; none of these are "files I was working on".
         (jmc-recentf-exclude-dir no-littering-var-directory)
         (jmc-recentf-exclude-dir no-littering-etc-directory)
         (jmc-recentf-exclude-dir (expand-file-name ".cache/" user-emacs-directory))
         (jmc-recentf-exclude-dir (expand-file-name "elpaca/" user-emacs-directory))
         (jmc-recentf-exclude-dir (expand-file-name "elpa/" user-emacs-directory))
         ;; Transient git plumbing (COMMIT_EDITMSG, rebase todo lists...).
         "/\\.git/"
         ;; Remote (TRAMP) entries: every cleanup pass stats its files, so
         ;; a single remote entry can block Emacs on a dead connection.
         "\\`/[a-zA-Z0-9-]+:"
         ;; macOS per-session temp trees.
         "\\`/private/var/folders/"))
  (recentf-mode 1))

;; =============================================================================
;; VISUAL AIDS & FORMATTING
;; =============================================================================

;; Enable line numbers, but only in programming modes.
;; -> This hook is the single source of truth for line numbers now that the
;;    redundant `global-display-line-numbers-mode` was removed from
;;    interface.el (it also numbered Dired, EWW, dashboard, and terminals).
;; -> Want numbers in prose too? Add the same hook for `text-mode-hook`.
(add-hook 'prog-mode-hook #'display-line-numbers-mode)
(setq-default display-line-numbers-width 3) ; Reserve 3 columns of width.

;; Enable visual word wrap in text modes (Markdown, plain text).
(add-hook 'text-mode-hook #'visual-line-mode)

;; Highlight the line the cursor is currently on.
;; -> No separate markdown-mode entry: markdown-mode derives from
;;    text-mode, so the text-mode hook already covers it.
(use-package hl-line
  :ensure nil ; Built-in
  :hook ((prog-mode . hl-line-mode)
         (text-mode . hl-line-mode)))

;; --- Bracket Pairing ---

;; Built-in `electric-pair-mode`: Automatically inserts closing brackets `()`, `[]`, `""`.
(use-package elec-pair
  :ensure nil ; Built-in — REQUIRED: with `use-package-always-ensure` (init.el),
					; omitting this makes Elpaca try to download a nonexistent
					; "elec-pair" package on every startup.
  :preface
  (defun jmc-electric-pair-inhibit-p (char)
    "Define when Emacs should *not* auto-insert a closing bracket."
    (or
     ;; 1. Never auto-pair while typing in the minibuffer command line.
     (minibufferp)
     ;; 2. Disable auto-pairing for `<`, `>`, and `~` (useful for HTML/XML/Markdown).
     (member char '(?< ?> ?~))
     ;; 3. Fallback to default conservative pairing logic for everything else.
     (electric-pair-conservative-inhibit char)))
  :config
  (setq electric-pair-inhibit-predicate #'jmc-electric-pair-inhibit-p)

  ;; Explicitly add curly braces `{}` to the pairing list.
  ;; -> `add-to-list` EXTENDS the default value. The old top-level
  ;;    `(setq electric-pair-pairs '((?\{ . ?\})))` REPLACED it, silently
  ;;    throwing away the default straight/curly quote pairs.
  (add-to-list 'electric-pair-pairs '(?\{ . ?\}))

  (electric-pair-mode t))

;; `rainbow-delimiters`: Color-codes matching brackets.
;; -> Makes deeply nested Lisp, JSON, or JavaScript much easier to read.
;; -> markdown-mode derives from text-mode; the text-mode hook covers it.
(use-package rainbow-delimiters
  :diminish rainbow-delimiters-mode
  :hook ((prog-mode . rainbow-delimiters-mode)
         (text-mode . rainbow-delimiters-mode)))

;; `supreme-brackets`: Advanced manual manipulation of brackets.
(use-package supreme-brackets
  :ensure (:host github :repo "J4VMC/supreme-brackets")
  :config
  (supreme-brackets-setup-extended-keybindings))

;; --- Indentation Guides ---
;; Bar colors follow `jmc-theme' (see init.el): Gruvbox Bright vs
;; Catppuccin Mocha accents, same seven-color rainbow order.
(use-package indent-bars
  :hook (prog-mode . indent-bars-mode)
  :custom
  ;; 1. Force character rendering
  (indent-bars-prefer-character t)
  (indent-bars-no-stipple-char ?│)

  ;; 2. Inactive bars: the theme's muted gray (Gruvbox bg3 / Catppuccin surface1)
  (indent-bars-color
   (if (eq jmc-theme 'catppuccin)
       '(highlight :face-bg nil :color "#45475a" :blend 1.0)
     '(highlight :face-bg nil :color "#665c54" :blend 1.0)))

  ;; 3. Depth colors: Red, Orange/Peach, Yellow, Green, Aqua/Teal, Blue, Purple/Mauve
  (indent-bars-color-by-depth
   (if (eq jmc-theme 'catppuccin)
       '(:palette ("#f38ba8" "#fab387" "#f9e2af" "#a6e3a1" "#94e2d5" "#89b4fa" "#cba6f7") :blend 1.0)
     '(:palette ("#fb4934" "#fe8019" "#fabd2f" "#b8bb26" "#8ec07c" "#83a598" "#d3869b") :blend 1.0)))

  ;; 4. Current depth: the theme's bright yellow (stands out beautifully)
  (indent-bars-highlight-current-depth
   (if (eq jmc-theme 'catppuccin)
       '(:color "#f9e2af" :blend 1.0)
     '(:color "#fabd2f" :blend 1.0)))

  :config
  (require 'indent-bars-ts)
  (setq indent-bars-treesit-support t))

;; Highlights semantic keywords like "TODO:", "FIXME:", and "NOTE:" in comments.
(use-package hl-todo
  :init (global-hl-todo-mode))

;; Renders `^L` (form feed) characters as clean horizontal divider lines.
(use-package page-break-lines
  :diminish page-break-lines-mode
  :config (global-page-break-lines-mode))

;; Automatically strip trailing whitespace from lines when saving a file.
(use-package whitespace-cleanup-mode
  :ensure (:host github :repo "purcell/whitespace-cleanup-mode")
  :defer t
  :diminish whitespace-cleanup-mode
  :hook (prog-mode . whitespace-cleanup-mode)
  :config (setq whitespace-cleanup-mode-preserve-point t))

;; =============================================================================
;; EDITING ENHANCEMENTS
;; =============================================================================

;; `crux`: A collection of essential utility commands.
;; -> E.g., `crux-rename-file-and-buffer`, `crux-duplicate-current-line-or-region`.
(use-package crux
  :defer t)

;; `hydra`: pop-up keybinding menus for REPEATABLE command groups — press
;; the entry key once, then drive everything with single keys until you
;; quit. Declared explicitly because the config now defines three hydras
;; of its own (it's also a treemacs dependency):
;;   * `C-c d h' — debugger stepping (debugger.el)
;;   * `C-c m'   — multiple cursors (below)
;;   * `C-c w'   — window management (interface.el)
;; `defhydra' is autoloaded, so `:defer t' is safe: the package loads the
;; first time a hydra is defined (each definition site defers too).
(use-package hydra
  :defer t)

;; Makes copy/cut commands apply to the *entire current line* if no text is highlighted.
(use-package whole-line-or-region
  :diminish whole-line-or-region-local-mode
  :config (whole-line-or-region-global-mode t))

;; `multiple-cursors`: VS Code-style multi-caret editing.
;; -> The five separate `:bind` keywords were merged into one list; repeated
;;    use-package keywords rely on undocumented merge behavior.
(use-package multiple-cursors
  :preface
  (defun jmc-mc-hydra-open ()
    "Load multiple-cursors (defining its hydra) and open the hydra."
    (interactive)
    (require 'multiple-cursors)
    (jmc-mc-hydra/body))
  :bind (("C-M-j"   . mc/edit-lines)               ; Add a cursor to each selected line.
         ("C->"     . mc/mark-next-like-this)      ; Add cursor at next matching word.
         ("C-<"     . mc/mark-previous-like-this)  ; Add cursor at prev matching word.
         ("C-c C-<" . mc/mark-all-like-this)       ; Add cursors at ALL matching words.
         ("C-M-="   . mc/mark-all-symbols-like-this)
         ("C-c m"   . jmc-mc-hydra-open))          ; One-key cursor placement (hydra).
  :config
  ;; Cursor-placement hydra: `C-c m', then single keys to grow/skip/shrink
  ;; the cursor set — no more chording `C->' repeatedly. A RED hydra: any
  ;; non-hydra key exits the menu AND does its normal thing, so when the
  ;; cursors are placed you just start typing.
  ;; -> Defined in `:config' (not top level): modules load before Elpaca
  ;;    installs packages, so `defhydra' only exists at runtime.
  (defhydra jmc-mc-hydra (:color red :hint nil)
    "
 Multiple Cursors  [%(mc/num-cursors) active]
 _n_: mark next     _N_: skip this, mark next     _u_: unmark next
 _p_: mark prev     _P_: skip this, mark prev     _U_: unmark prev
 _a_: mark all      _l_: cursor per selected line
 _q_: quit (keep cursors; type to edit, C-g to collapse)
"
    ("n" mc/mark-next-like-this)
    ("N" mc/skip-to-next-like-this)
    ("p" mc/mark-previous-like-this)
    ("P" mc/skip-to-previous-like-this)
    ("u" mc/unmark-next-like-this)
    ("U" mc/unmark-previous-like-this)
    ("a" mc/mark-all-like-this :color blue)
    ("l" mc/edit-lines :color blue)
    ("q" nil)))

;; `expreg`: Semantic selection expansion.
;; -> Press `M-J` repeatedly to grow selection: word -> string -> argument -> function.
(use-package expreg
  :bind ("M-J" . expreg-expand))

;; `visual-replace`: A cleaner, visual interface for find-and-replace.
;; -> NOTE: this block used to lack `:ensure t` and was therefore NEVER
;;    installed. With `use-package-always-ensure` (init.el) it now is.
(use-package visual-replace
  :defer t)

;; `drag-stuff`: Move lines or highlighted regions up/down using `M-up` and `M-down`.
(use-package drag-stuff
  :defer 1
  :diminish drag-stuff-mode
  :config
  (drag-stuff-global-mode 1)
  (drag-stuff-define-keys))

;; `avy`: Blazing fast on-screen navigation.
;; -> Triggers a search that overlays hotkeys on matches. Type the hotkey to jump instantly.
(use-package avy
  :bind (("C-c j" . avy-goto-line)      ; Jump to a specific visible line.
         ("s-j"   . avy-goto-char-timer))) ; Jump to any visible character sequence.

;; `rg`: Frontend for `ripgrep` (ultra-fast project search).
;; -> Integrated with `wgrep` to allow editing search results directly (project-wide replace).
(use-package rg
  :defer t
  :after transient
  :config
  (setq wgrep-auto-save-buffer t)
  (add-hook 'rg-mode-hook 'wgrep-rg-setup))

;; `vundo`: Visual Undo Tree.
;; -> Displays your undo history as a branching tree, allowing you to easily
;;    navigate past states without losing "undone" changes.
;; -> FIXED: the glyph setup moved from `:init` to `:config`.
;;    `vundo-unicode-symbols` is DEFINED BY vundo, which `:defer 1` hasn't
;;    loaded yet when `:init` runs — the setq signalled a void-variable
;;    error that use-package demoted to a message, so the undo tree has been
;;    silently rendering with ASCII glyphs instead of Unicode.
(use-package vundo
  :defer 1
  :config
  (setq vundo-glyph-alist vundo-unicode-symbols))

;; `undo-fu`: sane linear undo/redo COMMANDS on top of Emacs's undo system.
;; -> Stock Emacs "redo" means undoing an undo after breaking the chain,
;;    which is famously disorienting. undo-fu gives real undo/redo pairs
;;    while keeping the native undo data intact — so vundo's tree view and
;;    undo-fu's commands operate on the same history, no conflict.
;; -> BINDING NOTE: CUA mode owns `C-z` through its emulation keymap, which
;;    outranks the global map — a plain `C-z` binding here would be
;;    shadowed. `[remap undo]` catches the `undo' COMMAND instead, so
;;    CUA's C-z (and any other route to undo) lands on undo-fu.
(use-package undo-fu
  :bind (([remap undo] . undo-fu-only-undo)
         ("C-S-z" . undo-fu-only-redo)))

;; `undo-fu-session`: PERSIST undo history across Emacs restarts.
;; -> Saves each file's undo history on save/kill and restores it on visit,
;;    so the vundo tree reaches back into previous sessions. With backup
;;    files disabled above ("we rely on Git"), this is the safety net for
;;    mistakes in UNCOMMITTED work that would otherwise die with the
;;    session. History files live under `undo-fu-session-directory'
;;    (redirected into var/ by no-littering).
(use-package undo-fu-session
  :init
  (undo-fu-session-global-mode 1))

;; NOTE: `ctrlf' was REMOVED — in-buffer search is `consult-line' on `C-s'
;; (completion.el), consistent with the rest of the Vertico/Consult stack
;; (orderless matching, live preview, embark export). Removing ctrlf also
;; dropped its auto-cancel workaround, which ran on the GLOBAL
;; `post-command-hook' after every single command. `C-r' still runs the
;; stock `isearch-backward' as an escape hatch: occurrence-granular,
;; and — unlike minibuffer-based search — usable inside keyboard macros.

;; `dash` & `s`: Essential List and String manipulation libraries for Emacs Lisp.
(use-package dash)
(use-package s)

;; `evil-nerd-commenter`: Rapid code commenting/uncommenting (e.g., via `M-/`).
(use-package evil-nerd-commenter
  :defer 1
  :config
  (evilnc-default-hotkeys t))

;; NOTE: the `compat' library jinx depends on is declared in init.el (and
;; waited on), BEFORE any module loads — see the COMPAT section there for
;; why it must be explicit and early.

;; `jinx`: Fast, contextual spell checking backed by libenchant.
;; -> Context-aware: in programming modes it only checks comments, strings,
;;    and docstrings; in text modes it checks prose. Misspellings get a
;;    subtle underline; `M-$` pops correction candidates (in the Vertico
;;    UI, consistent with everything else).
;; -> SYSTEM DEPENDENCY: the enchant library — `brew install enchant`
;;    (tracked in the Brewfile). jinx compiles its native module against it
;;    on first load (needs pkgconf, also in the Brewfile).
(use-package jinx
  :hook (emacs-startup . global-jinx-mode)
  :bind (("M-$" . jinx-correct)
         ("C-M-$" . jinx-languages)))

(use-package which-key
  :ensure nil ; Built into Emacs 30+
  :init
  (which-key-mode)
  :config
  (setq which-key-idle-delay 0.5)    ; Pop up a bit faster
  (setq which-key-add-column-padding 1))

;; Built-in `repeat-mode`: repeat the last command's final key without the
;; prefix. After `C-x o` (other-window), just keep tapping `o` to cycle
;; windows; after `C-x {`/`}`, keep resizing with `{`/`}`; `M-,` after
;; `M-.` chains too. A transient hint shows the available repeat keys,
;; and any other key exits the repeat map.
(use-package repeat
  :ensure nil ; Built-in
  :init
  (repeat-mode 1))

;; =============================================================================
;; FINALIZE
;; =============================================================================

(provide 'editor)

;;; editor.el ends here
