;;; interface.el --- User interface customizations -*- lexical-binding: t; -*-

;;; Commentary:
;;
;; This module handles the visual appearance and core UI behavior of Emacs.
;;
;; We transform the default Emacs interface into a modern, aesthetically
;; pleasing development environment with:
;; 1. Font configuration (including Nerd Font icons and ligatures).
;; 2. Core UI improvements (transparency, scrolling, tabs).
;; 3. Icon packages for files, completions, and 'Dired'.
;; 4. A graphical dashboard (welcome screen).
;; 5. Enhanced mode-line and help system.
;;
;;; Code:

;; =============================================================================
;; COMPILER DECLARATIONS (SILENCE WARNINGS)
;; =============================================================================

(defvar display-time-format)
(defvar display-time-interval)
(defvar dashboard-projects-switch-function)
(defvar corfu-margin-formatters)
(defvar dimmer-buffer-exclusion-regexps)

(declare-function ligature-set-ligatures "ligature")
(declare-function global-ligature-mode "ligature")
(declare-function dashboard-setup-startup-hook "dashboard")
(declare-function dashboard-open "dashboard")
(declare-function dashboard-modify-heading-icons "dashboard")
(declare-function dashboard-icon-for-dir "dashboard")
(declare-function dashboard-icon-for-file "dashboard")
(declare-function global-colorful-mode "colorful-mode")
(declare-function dimmer-mode "dimmer")
(declare-function dimmer-configure-which-key "dimmer")
(declare-function dimmer-configure-magit "dimmer")
(declare-function dimmer-configure-hydra "dimmer")
;; Generated by `defhydra' inside `with-eval-after-load' below.
(declare-function jmc-window-hydra/body "interface")

;; =============================================================================
;; FONT CONFIGURATION
;; =============================================================================

;; Set the default font family and size.
;; -> The `:height` value of 150 represents 15.0 points.
(set-face-attribute 'default nil
                    :family "FiraCode Nerd Font"
                    :height 150
                    :weight 'normal)

;; Enable Nerd Font icons throughout Emacs.
;; -> Base fallback: use FiraCode Nerd Font for the classic icon range
;;    (U+E000..U+F8FF) so raw glyphs in terminals render even without the
;;    dedicated symbols font.
(set-fontset-font t '(#xe000 . #xf8ff) "FiraCode Nerd Font")

;; When the dedicated "Symbols Nerd Font Mono" is installed (via
;; `nerd-icons-install-fonts` or `brew install --cask
;; font-symbols-only-nerd-font`), route BOTH nerd-icon ranges to it:
;; its glyphs are strictly single-cell, unlike the double-width icons in
;; patched fonts, which render "cut in half" in treemacs.
;; -> The second range matters: Nerd Fonts v3 moved the material-design
;;    icons (nf-md-*, used heavily by treemacs-nerd-icons) to the
;;    SUPPLEMENTARY plane U+F0000..U+FFFFF, which the classic range
;;    doesn't cover at all.
(when (find-font (font-spec :family "Symbols Nerd Font Mono"))
  (set-fontset-font t '(#xe000 . #xf8ff) "Symbols Nerd Font Mono")
  (set-fontset-font t '(#xf0000 . #xfffff) "Symbols Nerd Font Mono"))

;; macOS-specific emoji font fallback.
;; -> Ensures emoji render correctly on macOS systems.
(when (string-equal system-type "darwin")
  (set-fontset-font t 'symbol "Apple Color Emoji" nil 'prepend))

;; -----------------------------------------------------------------------------
;; Ligatures (Combined Character Symbols)
;; -----------------------------------------------------------------------------
;; Ligatures replace character sequences like "=>" with single, stylized glyphs.
;; This improves readability in code without changing the underlying text.


(use-package ligature
  :config
  ;; Enable the "www" ligature universally.
  (ligature-set-ligatures 't '("www"))

  ;; Enable comprehensive ligature sets for programming modes.
  ;; -> Covers all Cascadia Code and Fira Code ligatures.
  ;; -> Examples: == === => != >= <= :: ... <!-- -->
  (ligature-set-ligatures 'prog-mode
                          '(;; Equals-based: == === ==== => =| =/=
                            ("=" (rx (+ (or ">" "<" "|" "/" "~" ":" "!" "="))))
                            ;; Semicolons: ;; ;;;
                            (";" (rx (+ ";")))
                            ;; Ampersands: && &&&
                            ("&" (rx (+ "&")))
                            ;; Exclamation: !! !!! != !== !~
                            ("!" (rx (+ (or "=" "!" "\." ":" "~"))))
                            ;; Question marks: ?? ??? ?: ?= ?.
                            ("?" (rx (or ":" "=" "\." (+ "?"))))
                            ;; Percent: %% %%%
                            ("%" (rx (+ "%")))
                            ;; Pipes: |> ||> ||| |-> || |==
                            ("|" (rx (+ (or ">" "<" "|" "/" ":" "!" "}" "\]"
                                            "-" "=" ))))
                            ;; Backslashes: \\ \\\ \/
                            ("\\" (rx (or "/" (+ "\\"))))
                            ;; Plus: ++ +++ +>
                            ("+" (rx (or ">" (+ "+"))))
                            ;; Colons: :: ::: := :> :<
                            (":" (rx (or ">" "<" "=" "//" ":=" (+ ":"))))
                            ;; Slashes: // /// /* /> /=
                            ("/" (rx (+ (or ">"  "<" "|" "/" "\\" "\*" ":" "!"
                                            "="))))
                            ;; Dots: .. ... .... .= .-
                            ("\." (rx (or "=" "-" "\?" "\.=" "\.<" (+ "\."))))
                            ;; Hyphens: -- --- -> ->> -|
                            ("-" (rx (+ (or ">" "<" "|" "~" "-"))))
                            ;; Asterisks: ** *** *> */
                            ("*" (rx (or ">" "/" ")" (+ "*"))))
                            ;; Multiple w's: www wwww
                            ("w" (rx (+ "w")))
                            ;; Less-than: <> <!-- <| <- <= <=> <<
                            ("<" (rx (+ (or "\+" "\*" "\$" "<" ">" ":" "~"  "!"
                                            "-"  "/" "|" "="))))
                            ;; Greater-than: >: >- >>- >= >== >>
                            (">" (rx (+ (or ">" "<" "|" "/" ":" "=" "-"))))
                            ;; Hash/Pound: #: #= #! #( #[ ## ###
                            ("#" (rx (or ":" "=" "!" "(" "\?" "\[" "{" "_(" "_"
                                         (+ "#"))))
                            ;; Tilde: ~~ ~~~ ~= ~- ~@ ~>
                            ("~" (rx (or ">" "=" "-" "@" "~>" (+ "~"))))
                            ;; Underscores: __ ___ _|_
                            ("_" (rx (+ (or "_" "|"))))
                            ;; Hex literals: 0xFF 0x12
                            ("0" (rx (and "x" (+ (in "A-F" "a-f" "0-9")))))
                            ;; Special letter combinations
                            "Fl"  "Tl"  "fi"  "fj"  "fl"  "ft"
                            ;; Miscellaneous symbols
                            "{|"  "[|"  "]#"  "(*"  "}#"  "$>"  "^="))

  ;; Activate ligatures globally.
  (global-ligature-mode t))

;; =============================================================================
;; CORE UI TWEAKS
;; =============================================================================

;; Enable window transparency.
;;
;; -> `alpha-background` (background-only transparency) is a PGTK/X-only
;;    feature: on the macOS NS build it is silently IGNORED, which is why the
;;    old `(alpha-background . 70)` setting never did anything.
;; -> On macOS we use the `alpha` frame parameter instead. Caveat: `alpha`
;;    makes the ENTIRE frame translucent — text included — so we use a much
;;    higher value than 70 to keep code readable. Format: (ACTIVE . INACTIVE).
;;    Tweak to taste; lower = more transparent.
(if (eq system-type 'darwin)
    (add-to-list 'default-frame-alist '(alpha . (92 . 88)))
  ;; Linux (PGTK/X): background-only transparency works as intended.
  (add-to-list 'default-frame-alist '(alpha-background . 70)))

;; Use a horizontal bar cursor instead of the default block.
;; -> Other options: 'block', 'box', '(bar . WIDTH)'.
;; -> The horizontal bar is less visually intrusive.
(setq-default cursor-type 'hbar)

;; Display column numbers in the mode-line.
;; -> Complements line numbers for precise navigation.
(column-number-mode 1)

;; Line numbers are enabled per-mode in `editor.el` (prog-mode hook).
;; -> The old `global-display-line-numbers-mode` here was redundant with that
;;    hook AND polluted Dired, EWW, the dashboard, and ghostel terminal
;;    buffers with meaningless line numbers. If you also want numbers in
;;    text modes, add a `text-mode-hook` next to the prog-mode one in
;;    editor.el rather than re-enabling the global mode.

;; Improve underline rendering.
;; -> Respects font descenders (the parts of letters that hang below the baseline).
;; -> Makes underlines under links and spell-check warnings look cleaner.
(setq-default x-underline-at-descent-line t)

;; Disable audible bell, enable visual flash.
;; -> On error or invalid action, the screen flashes instead of beeping.
;; -> Much less disruptive in quiet environments.
(setq visible-bell t)

;; Simplify yes/no prompts to y/n.
;; -> Saves keystrokes and speeds up common confirmations.
(setq use-short-answers t)

;; NEVER use native dialog boxes for questions — always the minibuffer.
;; -> When a command is invoked BY MOUSE (e.g. clicking the frame's close
;;    button), Emacs asks its questions ("save this buffer?", "server has
;;    clients; exit anyway?") through a native modal DIALOG instead of the
;;    minibuffer — and on the macOS port those dialogs regularly appear
;;    behind the frame or fail to take focus, so Emacs looks frozen while
;;    it silently waits for an answer. This was the "clicking close does
;;    nothing, must force-quit" bug. With dialogs off, every question lands
;;    predictably in the minibuffer.
(setq use-dialog-box nil)
(setq use-file-dialog nil)

;; Enable pixel-perfect smooth scrolling (Emacs 29+).
;; -> Provides a smoother, more modern scrolling experience.
;; -> Wrapped in a version check to avoid errors on older Emacs versions.
(when (>= emacs-major-version 29)
  (pixel-scroll-precision-mode 1))

;; Enable right-click context menus.
;; -> Provides familiar GUI-style interactions.
;; -> Enabled unconditionally: the old `display-graphic-p` guard evaluated to
;;    nil when Emacs starts as a daemon (no frame exists yet), and the mode is
;;    harmless in terminal frames anyway.
(context-menu-mode 1)

;; -----------------------------------------------------------------------------
;; Window Management Keybindings
;; -----------------------------------------------------------------------------

;; Navigate between split windows using Super (Cmd/Win) + Arrow keys.
;; -> Super-Left:  Move to the window on the left.
;; -> Super-Right: Move to the window on the right.
;; -> Super-Up:    Move to the window above.
;; -> Super-Down:  Move to the window below.
(global-set-key (kbd "s-<left>") 'windmove-left)
(global-set-key (kbd "s-<right>") 'windmove-right)
(global-set-key (kbd "s-<up>") 'windmove-up)
(global-set-key (kbd "s-<down>") 'windmove-down)

;; Window-management hydra on `C-c w': the operations that are painful as
;; one-shot chords because you always need SEVERAL of them — resizing above
;; all (stock C-x { / C-x ^ one keypress at a time is misery). Arrows
;; resize repeatedly; splits, balance, and close mixed in. RED hydra: any
;; non-hydra key (including s-<arrows> to change window) exits and acts
;; normally.
;; -> `defhydra' is deferred inside `with-eval-after-load' because modules
;;    load before Elpaca installs hydra; the entry command requires it.
(with-eval-after-load 'hydra
  (defhydra jmc-window-hydra (:color red :hint nil)
    "
 ^Resize^                 ^Split^        ^Act^
 _<left>_ / _<right>_ width   _2_: below     _=_: balance all
 _<up>_ / _<down>_ height    _3_: right     _x_: close this window
 ^ ^                      ^ ^            _1_: close the others
"
    ("<left>"  shrink-window-horizontally)
    ("<right>" enlarge-window-horizontally)
    ("<up>"    enlarge-window)
    ("<down>"  shrink-window)
    ("2" split-window-below)
    ("3" split-window-right)
    ("=" balance-windows)
    ("x" delete-window :color blue)
    ("1" delete-other-windows :color blue)
    ("q" nil)))

(defun jmc-window-hydra-open ()
  "Load hydra (defining the window hydra) and open it."
  (interactive)
  (require 'hydra)
  (jmc-window-hydra/body))

(global-set-key (kbd "C-c w") #'jmc-window-hydra-open)

;; -----------------------------------------------------------------------------
;; Mouse and Trackpad Settings
;; -----------------------------------------------------------------------------

;; Enable horizontal scrolling with trackpad or tilt-wheel.
;; -> Allows side-to-side scrolling for wide content.
(setq mouse-wheel-tilt-scroll t)

;; Use "natural" scrolling direction.
;; -> Content moves in the direction of your finger/scroll.
;; -> Matches macOS and modern touchpad behavior.
(setq mouse-wheel-flip-direction t)

;; -----------------------------------------------------------------------------
;; Tab Bar Configuration
;; -----------------------------------------------------------------------------

;; Enable the tab-bar (browser-style tabs at the top of the frame).
;; -> This is a minor mode: it must be CALLED as a function. The previous
;;    `(setq tab-bar-mode 1)` only set the variable and never activated it.
(tab-bar-mode 1)

;; Always show the tab bar, even with a single tab.
;; -> Options: t (always), 1 (only when MORE than one tab exists), nil (never).
;; -> The previous value of 1 meant the bar was HIDDEN with a single tab —
;;    the opposite of the intent.
(setq tab-bar-show t)

;; Keybindings for tab management.
;; -> Super-t: Open a new tab.
;; -> Super-l: Close the current tab.
;;    NOTE: lsp-mode's DEFAULT `lsp-keymap-prefix` is also "s-l", which
;;    would shadow this in every LSP buffer — but lang-server.el sets the
;;    prefix to "C-c l", so there is no conflict. Keep it that way if you
;;    ever touch `lsp-keymap-prefix`.
(global-set-key (kbd "s-t") 'tab-new)
(global-set-key (kbd "s-l") 'tab-close)

;; --- Clock ---
;; `display-time-mode' publishes the time via `global-mode-string', which
;; telephone-line renders in its misc-info segment (bottom right).
;; -> The tab-bar used to display the SAME `global-mode-string' a second
;;    time via `tab-bar-format-global' + `tab-bar-format-align-right';
;;    those entries were removed so the clock appears only at the bottom.
;; Minute resolution on purpose: the old `%T' + 1-second interval forced a
;; mode-line redisplay 86,400 times a day — measurable wake-up churn on a
;; laptop, for a seconds field nobody reads.
(setq display-time-format "%a %F %H:%M")
(setq display-time-interval 60)
;; Show only the clock — by default display-time also appends the system
;; load average to `global-mode-string', which is just noise here.
(setq display-time-default-load-average nil)
(display-time-mode)

;; -----------------------------------------------------------------------------
;; Visual Feedback for Edits
;; -----------------------------------------------------------------------------

;; Highlight lines changed relative to GIT (added/modified/deleted markers).
;; -> REPLACES line-reminder, which — despite the old comment claiming git
;;    awareness — only ever tracked UNSAVED in-buffer modifications.
;;    diff-hl diffs against the actual VC state, which is what the fringe
;;    marker should mean in a git-centric workflow.
(use-package diff-hl
  :hook ((prog-mode . diff-hl-mode)
         (conf-mode . diff-hl-mode))
  :custom
  ;; Use the RIGHT fringe: the left one is already contested by flycheck's
  ;; error indicators and treesit-fold's fold markers.
  (diff-hl-side 'right)
  :config
  ;; Update markers live as you type, not only after saving.
  (diff-hl-flydiff-mode 1)
  ;; Keep markers in sync with magit: refresh after commit/stage/revert.
  (add-hook 'magit-pre-refresh-hook  #'diff-hl-magit-pre-refresh)
  (add-hook 'magit-post-refresh-hook #'diff-hl-magit-post-refresh))

;; Preview color values inline.
;; -> Displays a color swatch next to hex codes like "#FFFFFF".
;; -> FIXED: same inert-package bug — `:defer t` with only `:config` meant the
;;    package never loaded and `global-colorful-mode` never ran.
(use-package colorful-mode
  :diminish
  :custom
  (colorful-use-prefix t)
  (colorful-only-strings 'only-prog)
  (css-fontify-colors nil) ; Let colorful-mode handle CSS colors
  :config
  ;; Also enable in helpful-mode buffers.
  (add-to-list 'global-colorful-modes 'helpful-mode)
  (global-colorful-mode 1))

;; =============================================================================
;; ICON PACKAGES
;; =============================================================================
;; Icons enhance visual clarity throughout Emacs, making it easier to
;; distinguish file types, completion candidates, and UI elements.

;; Core icon package: nerd-icons is THE single icon backend for this config
;; — dashboard, dirvish, minibuffer completion, corfu, and treemacs all
;; render from it. (all-the-icons and kind-icon are fully retired.)
;;
;; FONT REQUIREMENT: every glyph requests the family "Symbols Nerd Font
;; Mono" (nerd-icons' hardcoded default). If that font is missing, Emacs
;; falls back through the fontset above to plain FiraCode Nerd Font, whose
;; icon glyphs are DOUBLE-WIDTH — icons then render clipped ("cut in
;; half", most visibly in treemacs) or as hollow boxes. Fix once with
;; `M-x nerd-icons-install-fonts`, then restart. Do NOT "fix" it by
;; pointing `nerd-icons-font-family' at a patched font — that pins the
;; wrong glyph metrics permanently.
(use-package nerd-icons)

;; Add icons to minibuffer completion candidates.
;; -> Works with `marginalia` to show file-type icons during completion.
;; -> Replaces `all-the-icons-completion' with the nerd-icons equivalent.
(use-package nerd-icons-completion
  :after (marginalia nerd-icons)
  :hook (marginalia-mode . nerd-icons-completion-marginalia-setup)
  :init
  (nerd-icons-completion-mode))

;; NOTE: the `all-the-icons-dired' integration was REMOVED. Dirvish
;; (explorer.el) now renders its own icon column via the `nerd-icons'
;; attribute in every Dired buffer; layering a second icon package on top
;; produces doubled/misaligned icons — the same conflict that removed
;; `treemacs-icons-dired' from projects.el.

;; Add icons to Corfu completion popups.
;; -> Replaces `kind-icon', which was a whole SEPARATE icon system: SVG
;;    material icons downloaded over the network by svg-lib. nerd-icons-corfu
;;    renders the same kind indicators (function/variable/keyword/...) from
;;    the local nerd font instead — consistent with everything else, no
;;    network fetch, no icon cache directory.
(use-package nerd-icons-corfu
  :after (corfu nerd-icons)
  :config
  (add-to-list 'corfu-margin-formatters #'nerd-icons-corfu-formatter))

;; =============================================================================
;; DASHBOARD (STARTUP SCREEN)
;; =============================================================================
;; The dashboard replaces the default *scratch* buffer with a modern,
;; graphical welcome screen showing recent files and projects.

(use-package dashboard

  :init
  ;; Activate the dashboard natively during the startup sequence.
  ;; -> This blocks the screen from drawing until the dashboard is fully ready,
  ;;    preventing the ugly 0.5s flash of the *scratch* buffer.
  (dashboard-setup-startup-hook)

  ;; Make dashboard the default initial buffer.
  ;; -> Unless Emacs was started with a file argument (e.g., `emacs file.txt`).
  (unless (> (length command-line-args) 1)
    (setq initial-buffer-choice #'dashboard-open))

  :custom
  ;; Define the layout order.
  ;; -> Banner (logo) first, then items list.
  (dashboard-startupify-list '(dashboard-insert-banner
                               dashboard-insert-newline
                               dashboard-insert-items))

  ;; Use the built-in Emacs logo.
  (dashboard-startup-banner 'logo)

  ;; Center content both horizontally and vertically.
  ;; -> Creates a balanced, visually appealing layout.
  (dashboard-center-content t)
  (dashboard-vertically-center-content t)

  ;; Enable icons for section headings and files.
  (dashboard-set-heading-icons t)
  (dashboard-set-file-icons t)

  ;; PIN the icon backend explicitly. Dashboard AUTO-DETECTS its backend,
  ;; preferring nerd-icons over all-the-icons when both are installed —
  ;; so merely installing nerd-icons (for dirvish, explorer.el) silently
  ;; flipped the dashboard's backend and broke the all-the-icons heading
  ;; name below. Pinning makes the choice deterministic; the heading icon
  ;; name in :config matches this backend.
  (dashboard-icon-type 'nerd-icons)

  ;; Use Projectile for project discovery.
  (dashboard-projects-backend 'projectile)

  ;; Show 5 recent files and 5 recent projects.
  (dashboard-items '((recents . 5)
                     (projects . 5)))

  ;; Hide default footer and shortcuts.
  (dashboard-show-shortcuts nil)
  (dashboard-set-footer nil)

  :config
  ;; Customize the icon for the "Projects" section.
  ;; -> "nf-oct-file_directory" is the NERD-ICONS octicon name, matching
  ;;    the pinned `dashboard-icon-type' above. (The old "file-directory"
  ;;    was the all-the-icons spelling — invalid under nerd-icons.)
  (dashboard-modify-heading-icons '((projects . "nf-oct-file_directory")))

  ;; Clean up the *scratch* buffer after dashboard loads.
  ;; -> Since we're using dashboard, we don't need *scratch* anymore.
  (add-hook 'dashboard-after-initialize-hook
            (lambda ()
              (when (get-buffer "*scratch*")
                (kill-buffer "*scratch*")))))

;; -----------------------------------------------------------------------------
;; Dashboard Customizations
;; -----------------------------------------------------------------------------

;; Hide the cursor in the dashboard buffer.
;; -> The dashboard is non-interactive, so a visible cursor is unnecessary.
(defun jmc-dashboard-hide-cursor-h ()
  "Hide the cursor in the dashboard buffer."
  (setq-local cursor-type nil)
  (setq-local blink-cursor-mode nil))

(add-hook 'dashboard-mode-hook #'jmc-dashboard-hide-cursor-h)

;; Create a "lockdown" mode to make the dashboard completely static.
;; -> Disables all scrolling and movement keys.
;; -> Prevents accidental navigation that would break the centered layout.

;; Define a keymap that disables all movement commands.
(defvar dashboard-lock-keymap
  (let ((map (make-sparse-keymap)))
    ;; Disable arrow key navigation.
    (define-key map (kbd "<up>") 'ignore)
    (define-key map (kbd "<down>") 'ignore)
    (define-key map (kbd "<left>") 'ignore)
    (define-key map (kbd "<right>") 'ignore)
    ;; Disable page up/down.
    (define-key map (kbd "<prior>") 'ignore)
    (define-key map (kbd "<next>") 'ignore)
    ;; Disable Emacs scroll commands.
    (define-key map (kbd "C-v") 'ignore)
    (define-key map (kbd "M-v") 'ignore)
    ;; Disable mouse wheel scrolling.
    (define-key map (kbd "<wheel-up>") 'ignore)
    (define-key map (kbd "<wheel-down>") 'ignore)
    ;; Disable horizontal scrolling.
    (define-key map (kbd "<wheel-left>") 'ignore)
    (define-key map (kbd "<wheel-right>") 'ignore)
    ;; Disable jump-to-beginning/end commands.
    (define-key map (kbd "M-<") 'ignore)
    (define-key map (kbd "M->") 'ignore)
    map)
  "Keymap that disables all scrolling and navigation for the dashboard.")

;; Package the keymap into a toggleable minor mode.
(define-minor-mode dashboard-lock-mode
  "Lock the dashboard view by disabling all movement and scrolling."
  :init-value nil
  :lighter " Lock"
  :keymap dashboard-lock-keymap)

;; Setup function to initialize the locked dashboard state.
(defun setup-dashboard-lock ()
  "Configure window properties and activate dashboard lock mode."
  ;; Hide scroll bars.
  (set-window-scroll-bars (selected-window) nil nil)
  ;; Reset horizontal scroll position.
  (set-window-hscroll (selected-window) 0)
  ;; Prevent line wrapping.
  (setq-local truncate-lines t)
  ;; Activate the lock mode.
  (dashboard-lock-mode 1))

;; Activate the dashboard lock when dashboard-mode starts.
(add-hook 'dashboard-mode-hook #'setup-dashboard-lock)

(setq dashboard-projects-switch-function 'projectile-switch-project-by-name)

;; -----------------------------------------------------------------------------
;; Smarter Per-Project Icons
;; -----------------------------------------------------------------------------
;; By default, the icon backend's icon-for-dir function picks a project's
;; icon by matching patterns against the DIRECTORY NAME (nerd-icons and
;; all-the-icons both behave this way),
;; not by looking at what's actually inside it. Any project whose name
;; contains "test" (e.g. "rust-test", "php-test") matches the same generic
;; "test-dir" rule and gets an identical icon regardless of language.
;; -> Look for a well-known marker file instead, and borrow the (language-
;;    aware) file icon for that marker so the icon actually reflects the
;;    project's tech stack.

(defvar jmc-dashboard-project-marker-files
  '("Cargo.toml" "go.mod" "package.json" "composer.json" "Gemfile"
    "pyproject.toml" "requirements.txt" "Pipfile" "setup.py"
    "pom.xml" "build.gradle" "mix.exs" "Package.swift" "CMakeLists.txt")
  "Marker files checked, in order, to guess a project's language for icons.")

(defvar jmc-dashboard-project-marker-extensions
  '("\\.rs\\'" "\\.go\\'" "\\.py\\'" "\\.rb\\'" "\\.php\\'" "\\.sql\\'")
  "Fallback file-extension patterns for projects without a manifest file.
Only the project's top-level directory is scanned, to avoid recursing into
directories like `node_modules'.")

(defun jmc-dashboard-icon-for-project (orig-fn dir &rest args)
  "Prefer a language-specific icon for DIR based on marker files.
Falls back to calling ORIG-FN (`dashboard-icon-for-dir') with DIR and ARGS
when nothing recognizable is found."
  (let* ((exact (and (file-directory-p dir)
                     (seq-find (lambda (f) (file-exists-p (expand-file-name f dir)))
                               jmc-dashboard-project-marker-files)))
         (by-ext (and (not exact) (file-directory-p dir)
                      (seq-find (lambda (re) (directory-files dir nil re t))
				jmc-dashboard-project-marker-extensions)))
         (sample (and by-ext (car (directory-files dir nil by-ext t)))))
    (cond
     (exact (apply #'dashboard-icon-for-file exact args))
     (sample (apply #'dashboard-icon-for-file sample args))
     (t (apply orig-fn dir args)))))

(advice-add 'dashboard-icon-for-dir :around #'jmc-dashboard-icon-for-project)

;; =============================================================================
;; MODE-LINE AND HELP SYSTEM
;; =============================================================================

;; Use `telephone-line` for a modern, customizable mode-line.
;; -> The mode-line is the status bar at the bottom of each window.
;; -> Shows information like file name, git branch, line/column, errors, etc.
(use-package telephone-line
  :custom
  ;; Left-hand side segments.
  ;; -> Git branch, project name, minor modes, and buffer name.
  (telephone-line-lhs
   '((evil   . (telephone-line-vc-segment))
     (accent . (telephone-line-project-segment
                telephone-line-process-segment))
     (nil    . (telephone-line-minor-mode-segment
                telephone-line-buffer-segment))))

  ;; Right-hand side segments.
  ;; -> File encoding, error count, major mode, and position info.
  (telephone-line-rhs
   '((nil    . (telephone-line-atom-encoding-segment))
     (accent . (telephone-line-flycheck-segment
                telephone-line-major-mode-segment))
     (evil   . (telephone-line-misc-info-segment))))

  ;; Set the height of the mode-line.
  (telephone-line-height 24)

  :config
  (telephone-line-mode 1))

;; Replace the default help system with `helpful`.
;; -> Provides richer, more detailed help buffers.
;; -> Shows source code, references, and usage examples.
;; -> The keybindings moved from raw `global-set-key` calls into `:bind`,
;;    which also gives us proper lazy loading via autoloads.
;;    C-h f:   Describe function or macro.
;;    C-c C-d: Describe symbol at point.
;;    C-h F:   Describe function (functions only).
;;    C-h v:   Describe variable.
;;    C-h k:   Describe key binding.
;;    C-h x:   Describe command.
(use-package helpful
  :bind (("C-h f" . helpful-callable)
         ("C-c C-d" . helpful-at-point)
         ("C-h F" . helpful-function)
         ("C-h v" . helpful-variable)
         ("C-h k" . helpful-key)
         ("C-h x" . helpful-command)))

;; Dim inactive windows to improve focus.
;; -> Makes the active window brighter and more prominent.
;; -> Reduces visual clutter when working with multiple splits.
;; -> FIXED: the old block was `:defer t` with nothing to trigger loading, and
;;    `(setq dimmer-mode t)` only set a variable — dimmer never activated.
(use-package dimmer
  :config
  ;; Never dim the Corfu completion child frame.
  ;; -> Its window is technically "not selected" while you complete, so
  ;;    without this exclusion the popup itself would appear washed out.
  (add-to-list 'dimmer-buffer-exclusion-regexps "\\` \\*corfu")

  ;; Built-in compatibility tweaks for packages we actually use.
  ;; (hydra: our own hydras — `C-c w' here, `C-c d h', `C-c m' — plus
  ;;  treemacs' `?' helpful-hydra. Without this, the hydra hint window
  ;;  would render dimmed.)
  (dimmer-configure-which-key)
  (dimmer-configure-magit)
  (dimmer-configure-hydra)

  (dimmer-mode 1))

;; =============================================================================
;; FINALIZE
;; =============================================================================

(provide 'interface)

;;; interface.el ends here
