;;; interface.el --- User interface customizations -*- lexical-binding: t; -*-

;;; Commentary:
;;
;; This module handles the visual appearance and core UI behavior of Emacs.
;;
;; We transform the default Emacs interface into a modern, aesthetically
;; pleasing development environment with:
;; 1. Font configuration (including Nerd Font icons and ligatures).
;; 2. Core UI improvements (transparency, scrolling, tabs).
;; 3. Icon packages for files, completions, and 'Dired'.
;; 4. Enhanced mode-line and help system.
;;
;; NOTE: the startup screen lives in its own module now (welcome.el) —
;; the `dashboard' package it replaced used to be configured here.
;;
;;; Code:

;; =============================================================================
;; COMPILER DECLARATIONS (SILENCE WARNINGS)
;; =============================================================================

(defvar display-time-format)
(defvar display-time-interval)
(defvar corfu-margin-formatters)
(defvar dimmer-buffer-exclusion-regexps)
(defvar telephone-line-faces)

(declare-function ligature-set-ligatures "ligature")
(declare-function global-ligature-mode "ligature")
(declare-function global-colorful-mode "colorful-mode")
(declare-function dimmer-mode "dimmer")
(declare-function dimmer-configure-which-key "dimmer")
(declare-function dimmer-configure-magit "dimmer")
(declare-function dimmer-configure-hydra "dimmer")
;; Generated by `defhydra' inside `with-eval-after-load' below.
(declare-function jmc-window-hydra/body "interface")

;; =============================================================================
;; FONT CONFIGURATION
;; =============================================================================

;; Set the default font family and size.
;; -> The `:height` value of 150 represents 15.0 points.
(set-face-attribute 'default nil
                    :family "FiraCode Nerd Font"
                    :height 150
                    :weight 'normal)

;; Enable Nerd Font icons throughout Emacs.
;; -> Base fallback: use FiraCode Nerd Font for the classic icon range
;;    (U+E000..U+F8FF) so raw glyphs in terminals render even without the
;;    dedicated symbols font.
(set-fontset-font t '(#xe000 . #xf8ff) "FiraCode Nerd Font")

;; When the dedicated "Symbols Nerd Font Mono" is installed (via
;; `nerd-icons-install-fonts` or `brew install --cask
;; font-symbols-only-nerd-font`), route BOTH nerd-icon ranges to it:
;; its glyphs are strictly single-cell, unlike the double-width icons in
;; patched fonts, which render "cut in half" in treemacs.
;; -> The second range matters: Nerd Fonts v3 moved the material-design
;;    icons (nf-md-*, used heavily by treemacs-nerd-icons) to the
;;    SUPPLEMENTARY plane U+F0000..U+FFFFF, which the classic range
;;    doesn't cover at all.
(when (find-font (font-spec :family "Symbols Nerd Font Mono"))
  (set-fontset-font t '(#xe000 . #xf8ff) "Symbols Nerd Font Mono")
  (set-fontset-font t '(#xf0000 . #xfffff) "Symbols Nerd Font Mono"))

;; macOS-specific emoji font fallback.
;; -> Ensures emoji render correctly on macOS systems.
(when (string-equal system-type "darwin")
  (set-fontset-font t 'symbol "Apple Color Emoji" nil 'prepend))

;; -----------------------------------------------------------------------------
;; Ligatures (Combined Character Symbols)
;; -----------------------------------------------------------------------------
;; Ligatures replace character sequences like "=>" with single, stylized glyphs.
;; This improves readability in code without changing the underlying text.


(use-package ligature
  :config
  ;; Enable the "www" ligature universally.
  (ligature-set-ligatures 't '("www"))

  ;; Enable comprehensive ligature sets for programming modes.
  ;; -> Covers all Cascadia Code and Fira Code ligatures.
  ;; -> Examples: == === => != >= <= :: ... <!-- -->
  (ligature-set-ligatures 'prog-mode
                          '(;; Equals-based: == === ==== => =| =/=
                            ("=" (rx (+ (or ">" "<" "|" "/" "~" ":" "!" "="))))
                            ;; Semicolons: ;; ;;;
                            (";" (rx (+ ";")))
                            ;; Ampersands: && &&&
                            ("&" (rx (+ "&")))
                            ;; Exclamation: !! !!! != !== !~
                            ("!" (rx (+ (or "=" "!" "\." ":" "~"))))
                            ;; Question marks: ?? ??? ?: ?= ?.
                            ("?" (rx (or ":" "=" "\." (+ "?"))))
                            ;; Percent: %% %%%
                            ("%" (rx (+ "%")))
                            ;; Pipes: |> ||> ||| |-> || |==
                            ("|" (rx (+ (or ">" "<" "|" "/" ":" "!" "}" "\]"
                                            "-" "=" ))))
                            ;; Backslashes: \\ \\\ \/
                            ("\\" (rx (or "/" (+ "\\"))))
                            ;; Plus: ++ +++ +>
                            ("+" (rx (or ">" (+ "+"))))
                            ;; Colons: :: ::: := :> :<
                            (":" (rx (or ">" "<" "=" "//" ":=" (+ ":"))))
                            ;; Slashes: // /// /* /> /=
                            ("/" (rx (+ (or ">"  "<" "|" "/" "\\" "\*" ":" "!"
                                            "="))))
                            ;; Dots: .. ... .... .= .-
                            ("\." (rx (or "=" "-" "\?" "\.=" "\.<" (+ "\."))))
                            ;; Hyphens: -- --- -> ->> -|
                            ("-" (rx (+ (or ">" "<" "|" "~" "-"))))
                            ;; Asterisks: ** *** *> */
                            ("*" (rx (or ">" "/" ")" (+ "*"))))
                            ;; Multiple w's: www wwww
                            ("w" (rx (+ "w")))
                            ;; Less-than: <> <!-- <| <- <= <=> <<
                            ("<" (rx (+ (or "\+" "\*" "\$" "<" ">" ":" "~"  "!"
                                            "-"  "/" "|" "="))))
                            ;; Greater-than: >: >- >>- >= >== >>
                            (">" (rx (+ (or ">" "<" "|" "/" ":" "=" "-"))))
                            ;; Hash/Pound: #: #= #! #( #[ ## ###
                            ("#" (rx (or ":" "=" "!" "(" "\?" "\[" "{" "_(" "_"
                                         (+ "#"))))
                            ;; Tilde: ~~ ~~~ ~= ~- ~@ ~>
                            ("~" (rx (or ">" "=" "-" "@" "~>" (+ "~"))))
                            ;; Underscores: __ ___ _|_
                            ("_" (rx (+ (or "_" "|"))))
                            ;; Hex literals: 0xFF 0x12
                            ("0" (rx (and "x" (+ (in "A-F" "a-f" "0-9")))))
                            ;; Special letter combinations
                            "Fl"  "Tl"  "fi"  "fj"  "fl"  "ft"
                            ;; Miscellaneous symbols
                            "{|"  "[|"  "]#"  "(*"  "}#"  "$>"  "^="))

  ;; Activate ligatures globally.
  (global-ligature-mode t))

;; =============================================================================
;; CORE UI TWEAKS
;; =============================================================================

;; Enable window transparency.
;;
;; -> `alpha-background` (background-only transparency) is a PGTK/X-only
;;    feature: on the macOS NS build it is silently IGNORED, which is why the
;;    old `(alpha-background . 70)` setting never did anything.
;; -> On macOS we use the `alpha` frame parameter instead. Caveat: `alpha`
;;    makes the ENTIRE frame translucent — text included — so we use a much
;;    higher value than 70 to keep code readable. Format: (ACTIVE . INACTIVE).
;;    Tweak to taste; lower = more transparent.
(if (eq system-type 'darwin)
    (add-to-list 'default-frame-alist '(alpha . (92 . 88)))
  ;; Linux (PGTK/X): background-only transparency works as intended.
  (add-to-list 'default-frame-alist '(alpha-background . 70)))

;; Use a horizontal bar cursor instead of the default block.
;; -> Other options: 'block', 'box', '(bar . WIDTH)'.
;; -> The horizontal bar is less visually intrusive.
(setq-default cursor-type 'hbar)

;; Display column numbers in the mode-line.
;; -> Complements line numbers for precise navigation.
(column-number-mode 1)

;; Line numbers are enabled per-mode in `editor.el` (prog-mode hook).
;; -> The old `global-display-line-numbers-mode` here was redundant with that
;;    hook AND polluted Dired, EWW, the dashboard, and ghostel terminal
;;    buffers with meaningless line numbers. If you also want numbers in
;;    text modes, add a `text-mode-hook` next to the prog-mode one in
;;    editor.el rather than re-enabling the global mode.

;; Improve underline rendering.
;; -> Respects font descenders (the parts of letters that hang below the baseline).
;; -> Makes underlines under links and spell-check warnings look cleaner.
(setq-default x-underline-at-descent-line t)

;; Disable audible bell, enable visual flash.
;; -> On error or invalid action, the screen flashes instead of beeping.
;; -> Much less disruptive in quiet environments.
(setq visible-bell t)

;; Simplify yes/no prompts to y/n.
;; -> Saves keystrokes and speeds up common confirmations.
(setq use-short-answers t)

;; NEVER use native dialog boxes for questions — always the minibuffer.
;; -> When a command is invoked BY MOUSE (e.g. clicking the frame's close
;;    button), Emacs asks its questions ("save this buffer?", "server has
;;    clients; exit anyway?") through a native modal DIALOG instead of the
;;    minibuffer — and on the macOS port those dialogs regularly appear
;;    behind the frame or fail to take focus, so Emacs looks frozen while
;;    it silently waits for an answer. This was the "clicking close does
;;    nothing, must force-quit" bug. With dialogs off, every question lands
;;    predictably in the minibuffer.
(setq use-dialog-box nil)
(setq use-file-dialog nil)

;; Enable pixel-perfect smooth scrolling (Emacs 29+).
;; -> Provides a smoother, more modern scrolling experience.
;; -> Wrapped in a version check to avoid errors on older Emacs versions.
(when (>= emacs-major-version 29)
  (pixel-scroll-precision-mode 1))

;; Enable right-click context menus.
;; -> Provides familiar GUI-style interactions.
;; -> Enabled unconditionally: the old `display-graphic-p` guard evaluated to
;;    nil when Emacs starts as a daemon (no frame exists yet), and the mode is
;;    harmless in terminal frames anyway.
(context-menu-mode 1)

;; -----------------------------------------------------------------------------
;; Window Management Keybindings
;; -----------------------------------------------------------------------------

;; Navigate between split windows using Super (Cmd/Win) + Arrow keys.
;; -> Super-Left:  Move to the window on the left.
;; -> Super-Right: Move to the window on the right.
;; -> Super-Up:    Move to the window above.
;; -> Super-Down:  Move to the window below.
(global-set-key (kbd "s-<left>") 'windmove-left)
(global-set-key (kbd "s-<right>") 'windmove-right)
(global-set-key (kbd "s-<up>") 'windmove-up)
(global-set-key (kbd "s-<down>") 'windmove-down)

;; Window-management hydra on `C-c w': the operations that are painful as
;; one-shot chords because you always need SEVERAL of them — resizing above
;; all (stock C-x { / C-x ^ one keypress at a time is misery). Arrows
;; resize repeatedly; splits, balance, and close mixed in. RED hydra: any
;; non-hydra key (including s-<arrows> to change window) exits and acts
;; normally.
;; -> `defhydra' is deferred inside `with-eval-after-load' because modules
;;    load before Elpaca installs hydra; the entry command requires it.
(with-eval-after-load 'hydra
  (defhydra jmc-window-hydra (:color red :hint nil)
    "
 ^Resize^                 ^Split^        ^Act^
 _<left>_ / _<right>_ width   _2_: below     _=_: balance all
 _<up>_ / _<down>_ height    _3_: right     _x_: close this window
 ^ ^                      ^ ^            _1_: close the others
"
    ("<left>"  shrink-window-horizontally)
    ("<right>" enlarge-window-horizontally)
    ("<up>"    enlarge-window)
    ("<down>"  shrink-window)
    ("2" split-window-below)
    ("3" split-window-right)
    ("=" balance-windows)
    ("x" delete-window :color blue)
    ("1" delete-other-windows :color blue)
    ("q" nil)))

(defun jmc-window-hydra-open ()
  "Load hydra (defining the window hydra) and open it."
  (interactive)
  (require 'hydra)
  (jmc-window-hydra/body))

(global-set-key (kbd "C-c w") #'jmc-window-hydra-open)

;; -----------------------------------------------------------------------------
;; Mouse and Trackpad Settings
;; -----------------------------------------------------------------------------

;; Enable horizontal scrolling with trackpad or tilt-wheel.
;; -> Allows side-to-side scrolling for wide content.
(setq mouse-wheel-tilt-scroll t)

;; Use "natural" scrolling direction.
;; -> Content moves in the direction of your finger/scroll.
;; -> Matches macOS and modern touchpad behavior.
(setq mouse-wheel-flip-direction t)

;; -----------------------------------------------------------------------------
;; Tab Bar Configuration
;; -----------------------------------------------------------------------------

;; Enable the tab-bar (browser-style tabs at the top of the frame).
;; -> This is a minor mode: it must be CALLED as a function. The previous
;;    `(setq tab-bar-mode 1)` only set the variable and never activated it.
(tab-bar-mode 1)

;; Always show the tab bar, even with a single tab.
;; -> Options: t (always), 1 (only when MORE than one tab exists), nil (never).
;; -> The previous value of 1 meant the bar was HIDDEN with a single tab —
;;    the opposite of the intent.
(setq tab-bar-show t)

;; Keybindings for tab management.
;; -> Super-t: Open a new tab.
;; -> Super-l: Close the current tab.
;;    NOTE: lsp-mode's DEFAULT `lsp-keymap-prefix` is also "s-l", which
;;    would shadow this in every LSP buffer — but lang-server.el sets the
;;    prefix to "C-c l", so there is no conflict. Keep it that way if you
;;    ever touch `lsp-keymap-prefix`.
(global-set-key (kbd "s-t") 'tab-new)
(global-set-key (kbd "s-l") 'tab-close)

;; --- Clock ---
;; `display-time-mode' publishes the time via `global-mode-string', which
;; telephone-line renders in its misc-info segment (bottom right).
;; -> The tab-bar used to display the SAME `global-mode-string' a second
;;    time via `tab-bar-format-global' + `tab-bar-format-align-right';
;;    those entries were removed so the clock appears only at the bottom.
;; Minute resolution on purpose: the old `%T' + 1-second interval forced a
;; mode-line redisplay 86,400 times a day — measurable wake-up churn on a
;; laptop, for a seconds field nobody reads.
(setq display-time-format "%a %F %H:%M")
(setq display-time-interval 60)
;; Show only the clock — by default display-time also appends the system
;; load average to `global-mode-string', which is just noise here.
(setq display-time-default-load-average nil)
(display-time-mode)

;; -----------------------------------------------------------------------------
;; Visual Feedback for Edits
;; -----------------------------------------------------------------------------

;; Highlight lines changed relative to GIT (added/modified/deleted markers).
;; -> REPLACES line-reminder, which — despite the old comment claiming git
;;    awareness — only ever tracked UNSAVED in-buffer modifications.
;;    diff-hl diffs against the actual VC state, which is what the fringe
;;    marker should mean in a git-centric workflow.
(use-package diff-hl
  :hook ((prog-mode . diff-hl-mode)
         (conf-mode . diff-hl-mode))
  :custom
  ;; Use the RIGHT fringe: the left one is already contested by flycheck's
  ;; error indicators and treesit-fold's fold markers.
  (diff-hl-side 'right)
  :config
  ;; Update markers live as you type, not only after saving.
  (diff-hl-flydiff-mode 1)
  ;; Keep markers in sync with magit: refresh after commit/stage/revert.
  (add-hook 'magit-pre-refresh-hook  #'diff-hl-magit-pre-refresh)
  (add-hook 'magit-post-refresh-hook #'diff-hl-magit-post-refresh))

;; Preview color values inline.
;; -> Displays a color swatch next to hex codes like "#FFFFFF".
;; -> FIXED: same inert-package bug — `:defer t` with only `:config` meant the
;;    package never loaded and `global-colorful-mode` never ran.
(use-package colorful-mode
  :diminish
  :custom
  (colorful-use-prefix t)
  (colorful-only-strings 'only-prog)
  (css-fontify-colors nil) ; Let colorful-mode handle CSS colors
  :config
  ;; Also enable in helpful-mode buffers.
  (add-to-list 'global-colorful-modes 'helpful-mode)
  (global-colorful-mode 1))

;; =============================================================================
;; ICON PACKAGES
;; =============================================================================
;; Icons enhance visual clarity throughout Emacs, making it easier to
;; distinguish file types, completion candidates, and UI elements.

;; Core icon package: nerd-icons is THE single icon backend for this config
;; — the welcome screen, dirvish, minibuffer completion, corfu, and treemacs
;; all render from it. (all-the-icons and kind-icon are fully retired.)
;;
;; FONT REQUIREMENT: every glyph requests the family "Symbols Nerd Font
;; Mono" (nerd-icons' hardcoded default). If that font is missing, Emacs
;; falls back through the fontset above to plain FiraCode Nerd Font, whose
;; icon glyphs are DOUBLE-WIDTH — icons then render clipped ("cut in
;; half", most visibly in treemacs) or as hollow boxes. Fix once with
;; `M-x nerd-icons-install-fonts`, then restart. Do NOT "fix" it by
;; pointing `nerd-icons-font-family' at a patched font — that pins the
;; wrong glyph metrics permanently.
(use-package nerd-icons)

;; Add icons to minibuffer completion candidates.
;; -> Works with `marginalia` to show file-type icons during completion.
;; -> Replaces `all-the-icons-completion' with the nerd-icons equivalent.
(use-package nerd-icons-completion
  :after (marginalia nerd-icons)
  :hook (marginalia-mode . nerd-icons-completion-marginalia-setup)
  :init
  (nerd-icons-completion-mode))

;; NOTE: the `all-the-icons-dired' integration was REMOVED. Dirvish
;; (explorer.el) now renders its own icon column via the `nerd-icons'
;; attribute in every Dired buffer; layering a second icon package on top
;; produces doubled/misaligned icons — the same conflict that removed
;; `treemacs-icons-dired' from projects.el.

;; Add icons to Corfu completion popups.
;; -> Replaces `kind-icon', which was a whole SEPARATE icon system: SVG
;;    material icons downloaded over the network by svg-lib. nerd-icons-corfu
;;    renders the same kind indicators (function/variable/keyword/...) from
;;    the local nerd font instead — consistent with everything else, no
;;    network fetch, no icon cache directory.
(use-package nerd-icons-corfu
  :after (corfu nerd-icons)
  :config
  (add-to-list 'corfu-margin-formatters #'nerd-icons-corfu-formatter))

;; =============================================================================
;; MODE-LINE AND HELP SYSTEM
;; =============================================================================

;; Use `telephone-line` for a modern, customizable mode-line.
;; -> The mode-line is the status bar at the bottom of each window.
;; -> Shows information like file name, git branch, line/column, errors, etc.
;;
;; -----------------------------------------------------------------------------
;; Theme-agnostic, high-contrast palette
;; -----------------------------------------------------------------------------
;; Neither of our themes styles telephone-line, so out of the box the
;; accent sections kept upstream's neutral "grey22" (clashing with any
;; warm palette), and the sections previously on the `evil' color slot
;; silently fell back to the plain `mode-line' face — without evil-mode,
;; `telephone-line-modal-face' resolves `evil' to `mode-line' — leaving
;; the whole bar one muddy strip (gruvbox: light2 on dark3, a ~3.4:1
;; contrast ratio, below even WCAG AA).
;;
;; Rather than a hardcoded per-theme color table, the palette is DERIVED
;; from whatever theme is active, each time one is enabled:
;;   * base sections:   the editor background raised one step toward the
;;                      foreground, with the theme's FULL-strength
;;                      foreground as text — this is where the old setup
;;                      lost contrast (themes dim their mode-line text).
;;   * accent sections: raised a second step -> a clear visual hierarchy.
;;   * end blocks (`jmc-strong' slot): a vivid theme color carrying the
;;                      editor background as bold text. The color is the
;;                      first sufficiently readable candidate among the
;;                      `warning' / function-name / keyword faces, so
;;                      gruvbox-dark-hard lands on its signature yellow
;;                      (#fabd2f) and catppuccin on its yellow — with a
;;                      contrast-checked fallback for any future theme.
;; Everything recomputes via `enable-theme-functions', so switching
;; themes restyles the bar with zero per-theme code here.

(defface jmc-telephone-strong-active
  '((t (:weight bold :inherit telephone-line-accent-active)))
  "End-block face for the mode-line's outermost sections.
Actual colors are derived from the active theme by
`jmc-modeline-apply-palette'; this spec is only the pre-theme fallback.")

(defface jmc-telephone-strong-inactive
  '((t (:inherit telephone-line-accent-inactive)))
  "Inactive-window counterpart of `jmc-telephone-strong-active'.")

(defun jmc-modeline--hex (color)
  "Normalize COLOR to a \"#rrggbb\" string, or nil for unusable values."
  (when (and (stringp color) (not (string= color "unspecified")))
    (when-let* ((rgb (color-name-to-rgb color)))
      (apply #'color-rgb-to-hex (append rgb '(2))))))

(defun jmc-modeline--blend (from to alpha)
  "Blend color FROM toward color TO by ALPHA (0.0 keeps FROM, 1.0 is TO)."
  (pcase-let ((`(,r1 ,g1 ,b1) (color-name-to-rgb from))
              (`(,r2 ,g2 ,b2) (color-name-to-rgb to)))
    (color-rgb-to-hex (+ (* (- 1 alpha) r1) (* alpha r2))
                      (+ (* (- 1 alpha) g1) (* alpha g2))
                      (+ (* (- 1 alpha) b1) (* alpha b2))
                      2)))

(defun jmc-modeline--contrast (c1 c2)
  "Return the WCAG contrast ratio (1.0-21.0) between colors C1 and C2."
  (let* ((lum (lambda (c)
                (pcase-let ((`(,r ,g ,b)
                             (mapcar (lambda (v)
                                       (if (<= v 0.03928)
                                           (/ v 12.92)
                                         (expt (/ (+ v 0.055) 1.055) 2.4)))
                                     (color-name-to-rgb c))))
                  (+ (* 0.2126 r) (* 0.7152 g) (* 0.0722 b)))))
         (l1 (funcall lum c1))
         (l2 (funcall lum c2)))
    (/ (+ (max l1 l2) 0.05) (+ (min l1 l2) 0.05))))

(defun jmc-modeline--pop-color (bg fg)
  "Pick the end-block color for a theme whose canvas is BG.
The first candidate face whose foreground reads on BG with at least a
4.5:1 (WCAG AA) contrast ratio wins; FG is the last-resort fallback."
  (or (seq-find (lambda (color)
                  (and color (>= (jmc-modeline--contrast color bg) 4.5)))
                (mapcar (lambda (face)
                          (jmc-modeline--hex
                           (face-attribute face :foreground nil t)))
                        '(warning
                          font-lock-function-name-face
                          font-lock-keyword-face)))
      fg))

(defun jmc-modeline-apply-palette (&rest _)
  "Derive the mode-line palette from the active theme's own colors.
Runs at startup and from `enable-theme-functions' (the trailing hook of
every `enable-theme'), so it always has the final theme values — and
always wins over whatever the theme set on `mode-line'."
  (require 'color)
  (let* ((bg (or (jmc-modeline--hex (face-attribute 'default :background))
                 "#1d2021")) ; tty fallback: unspecified -> gruvbox bg0_h
         (fg (or (jmc-modeline--hex (face-attribute 'default :foreground))
                 "#ebdbb2"))
         (pop (jmc-modeline--pop-color bg fg))
         (base-bg (jmc-modeline--blend bg fg 0.12))
         (accent-bg (jmc-modeline--blend bg fg 0.24))
         (inactive-bg (jmc-modeline--blend bg fg 0.06))
         (dim-fg (jmc-modeline--blend fg bg 0.45)))
    ;; Base sections ('nil slot). Full-strength foreground on a slightly
    ;; raised background — the single biggest contrast win over the
    ;; themes' own dimmed mode-line text.
    (set-face-attribute 'mode-line nil
                        :background base-bg :foreground fg :box nil)
    (set-face-attribute 'mode-line-inactive nil
                        :background inactive-bg :foreground dim-fg :box nil)
    ;; Accent sections: one more step up, replacing upstream's grey22.
    (set-face-attribute 'telephone-line-accent-active nil
                        :background accent-bg :foreground fg)
    (set-face-attribute 'telephone-line-accent-inactive nil
                        :background base-bg :foreground dim-fg)
    ;; End blocks: vivid color, editor background as bold text.
    (set-face-attribute 'jmc-telephone-strong-active nil
                        :background pop :foreground bg :weight 'bold)
    (set-face-attribute 'jmc-telephone-strong-inactive nil
                        :background accent-bg :foreground dim-fg
                        :weight 'normal)
    ;; Segment detail faces: project name in the pop color; de-emphasized
    ;; text in the blended gray instead of upstream's hardcoded
    ;; "light green" / "dim grey" (neither belongs to any theme).
    (set-face-attribute 'telephone-line-projectile nil
                        :foreground pop :weight 'bold)
    (set-face-attribute 'telephone-line-unimportant nil
                        :foreground dim-fg)))

(use-package telephone-line
  :custom
  ;; Left-hand side segments.
  ;; -> Git branch (strong end block), project name, minor modes, buffer.
  (telephone-line-lhs
   '((jmc-strong . (telephone-line-vc-segment))
     (accent     . (telephone-line-project-segment
                    telephone-line-process-segment))
     (nil        . (telephone-line-minor-mode-segment
                    telephone-line-buffer-segment))))

  ;; Right-hand side segments.
  ;; -> File encoding, error count, major mode; clock/workspace in the
  ;;    strong end block.
  (telephone-line-rhs
   '((nil        . (telephone-line-atom-encoding-segment))
     (accent     . (telephone-line-flycheck-segment
                    telephone-line-major-mode-segment))
     (jmc-strong . (telephone-line-misc-info-segment))))

  ;; Set the height of the mode-line.
  (telephone-line-height 24)

  :config
  ;; Register the custom `jmc-strong' color slot used in lhs/rhs above.
  ;; MUST precede `telephone-line-mode', which compiles the format.
  (add-to-list 'telephone-line-faces
               '(jmc-strong . (jmc-telephone-strong-active
                               . jmc-telephone-strong-inactive)))

  ;; Apply the derived palette now (the startup theme loaded long before
  ;; this package), and re-derive it on every future theme switch.
  (jmc-modeline-apply-palette)
  (add-hook 'enable-theme-functions #'jmc-modeline-apply-palette)

  (telephone-line-mode 1))

;; Replace the default help system with `helpful`.
;; -> Provides richer, more detailed help buffers.
;; -> Shows source code, references, and usage examples.
;; -> The keybindings moved from raw `global-set-key` calls into `:bind`,
;;    which also gives us proper lazy loading via autoloads.
;;    C-h f:   Describe function or macro.
;;    C-c C-d: Describe symbol at point.
;;    C-h F:   Describe function (functions only).
;;    C-h v:   Describe variable.
;;    C-h k:   Describe key binding.
;;    C-h x:   Describe command.
(use-package helpful
  :bind (("C-h f" . helpful-callable)
         ("C-c C-d" . helpful-at-point)
         ("C-h F" . helpful-function)
         ("C-h v" . helpful-variable)
         ("C-h k" . helpful-key)
         ("C-h x" . helpful-command)))

;; Dim inactive windows to improve focus.
;; -> Makes the active window brighter and more prominent.
;; -> Reduces visual clutter when working with multiple splits.
;; -> FIXED: the old block was `:defer t` with nothing to trigger loading, and
;;    `(setq dimmer-mode t)` only set a variable — dimmer never activated.
(use-package dimmer
  :config
  ;; Never dim the Corfu completion child frame.
  ;; -> Its window is technically "not selected" while you complete, so
  ;;    without this exclusion the popup itself would appear washed out.
  (add-to-list 'dimmer-buffer-exclusion-regexps "\\` \\*corfu")

  ;; Built-in compatibility tweaks for packages we actually use.
  ;; (hydra: our own hydras — `C-c w' here, `C-c d h', `C-c m' — plus
  ;;  treemacs' `?' helpful-hydra. Without this, the hydra hint window
  ;;  would render dimmed.)
  (dimmer-configure-which-key)
  (dimmer-configure-magit)
  (dimmer-configure-hydra)

  (dimmer-mode 1))

;; =============================================================================
;; FINALIZE
;; =============================================================================

(provide 'interface)

;;; interface.el ends here
